# https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]

python:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'

python_impl:
  - '3.8.* *_cpython'
  - '3.9.* *_cpython'
  - '3.10.* *_cpython'
  - '3.11.* *_cpython'
  - '3.12.* *_cpython'

numpy:
  - '1.22.*'
  - '1.22.*'
  - '1.22.*'
  - '1.22.*'
  - '1.22.*'
